# Generated by Django 3.0.2 on 2020-07-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtitle', models.CharField(max_length=100)),
                ('roomno', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=20)),
                ('availibility', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image/')),
                ('image1', models.ImageField(upload_to='image/')),
                ('timeStamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
