# Generated by Django 3.0.2 on 2020-07-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
