# Generated by Django 3.0.2 on 2020-12-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0004_auto_20201212_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
