# Generated by Django 3.0.2 on 2020-07-22 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_imggal_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='imggal',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
            preserve_default=False,
        ),
    ]
