# Generated by Django 3.0.2 on 2020-07-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_imggal_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imggal',
            name='timeStamp',
        ),
    ]
