# Generated by Django 3.0.2 on 2020-07-22 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_imggal_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='imggal',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
