# Generated by Django 3.0.2 on 2020-02-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='Post',
        ),
    ]
