# Generated by Django 3.0.2 on 2020-05-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
