# Generated by Django 3.0.2 on 2020-07-23 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200723_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='carusel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/'),
            preserve_default=False,
        ),
    ]
