# Generated by Django 3.0.2 on 2020-07-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_carusel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carusel',
            name='image1',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='image2',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
