# Generated by Django 3.0.2 on 2020-05-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('auther', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
